# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os: windows

julia:
  - 1.2

script:
  # ver: Windows Server 1803

  - cd c:\\julia\\bin
  - ./julia.exe -E "1"

  - cp -r c:\\julia c:\\테스트
  - rm c:\\julia\\lib\\julia\\sys.dll

  - cd c:\\테스트\\bin
  - ./julia.exe -E "1"

  - cd c:\\julia\\bin
  - ./julia.exe -E "1" -H c:\\테스트\\bin
