environment:
  matrix:
  - julia_version: 1.2

platform:
  - x64 # 64-bit

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build: off

init:
- ps: Set-WinSystemLocale ko-KR

test_script:
  - ver
  - ps: |

      cd c:\\julia\\bin
      ./julia.exe -E "1"

      cp -r c:\\julia c:\\테스트
      rm c:\\julia\\lib\\julia\\sys.dll

      cd c:\\테스트\\bin
      ./julia.exe -E "1"

      cd c:\\julia\\bin
      ./julia.exe -E "1" -H c:\\테스트\\bin
